name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040507'
    - '#beb5ab'
    - '#00c7fe'
    - '#fe003c'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
